runs-on: windows-latest

steps:
  - uses: actions/checkout@v4
  - name: Setup JDK
    uses: actions/setup-java@v4
    with:
      java-version: '17'
      distribution: 'temurin'
  - name: Build JAR
    run: mvn clean package
  - name: Gerar EXE com jpackage
    run: |
      jpackage --type exe --input target/ --name RoboBarueri --main-jar meuprojeto-1.0-jar-with-dependencies.jar --main-class robo.barueri.Main
  - name: Upload EXE
    uses: actions/upload-artifact@v4
    with:
      name: executavel-exe
      path: RoboBarueri.exe